version: '3'

services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=password
    ports:
      - 54321:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "psql postgres://local:password@localhost:5432/gis -c 'SELECT 1;'" ]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgis_data: